import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import bg from '../public/images/BG.png';
import { Web3Provider } from "@ethersproject/providers";
import { Web3ReactProvider } from "@web3-react/core";
import connectors from "@/utils/connectors";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Web3ReactProvider connectors={connectors}>
      <html lang="en">
        <body style={{ backgroundImage: `url(${bg.src})` }} className={inter.className}>{children}</body>
      </html>
    </Web3ReactProvider>
  );
}
